# Generated by Django 4.2.30 on 2026-06-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsoCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('weight', models.FloatField(default=1.0, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Característica ISO 25010',
                'verbose_name_plural': 'Características ISO 25010',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IsoSubcharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcharacteristics', to='quality.isocharacteristic', verbose_name='Característica')),
            ],
            options={
                'verbose_name': 'Subcaracterística ISO 25010',
                'verbose_name_plural': 'Subcaracterísticas ISO 25010',
                'ordering': ['characteristic__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Nombre de métrica')),
                ('value', models.FloatField(verbose_name='Valor actual')),
                ('target', models.FloatField(verbose_name='Valor objetivo')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('status', models.CharField(choices=[('COMPLIANT', 'Cumple'), ('NON_COMPLIANT', 'No cumple'), ('WARNING', 'En observación'), ('NOT_MEASURED', 'No medido')], default='NOT_MEASURED', max_length=20, verbose_name='Estado')),
                ('formula', models.TextField(blank=True, verbose_name='Fórmula de cálculo')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de medición')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='quality.isocharacteristic', verbose_name='Característica')),
                ('subcharacteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='quality.isosubcharacteristic', verbose_name='Subcaracterística')),
            ],
            options={
                'verbose_name': 'Métrica de calidad',
                'verbose_name_plural': 'Métricas de calidad',
                'ordering': ['characteristic__code', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('NC', 'No Conformidad'), ('OBS', 'Observación'), ('STR', 'Fortaleza')], max_length=10, verbose_name='Tipo de hallazgo')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítico'), ('MAJOR', 'Mayor'), ('MINOR', 'Menor')], max_length=10, verbose_name='Severidad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('evidence', models.JSONField(blank=True, null=True, verbose_name='Evidencia')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Acción correctiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='quality.isocharacteristic', verbose_name='Característica')),
            ],
            options={
                'verbose_name': 'Hallazgo de auditoría',
                'verbose_name_plural': 'Hallazgos de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
