# Generated by Django 4.2.30 on 2026-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymetric',
            name='level_descriptions',
            field=models.JSONField(blank=True, null=True, verbose_name='Descriptores por nivel'),
        ),
    ]
