# Generated by Django 4.2.30 on 2026-06-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('LOGOUT', 'Cierre de sesión'), ('CAPTURE', 'Captura de asistencia'), ('CAPTURE_FAILED', 'Captura fallida'), ('EXCEPTION', 'Justificación de inasistencia'), ('USER_CREATE', 'Creación de usuario'), ('USER_UPDATE', 'Actualización de usuario'), ('USER_DEACTIVATE', 'Desactivación de usuario'), ('USER_REACTIVATE', 'Reactivación de usuario'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('STUDENT_CREATE', 'Creación de estudiante'), ('STUDENT_UPDATE', 'Actualización de estudiante'), ('SCHEDULE_CREATE', 'Creación de horario'), ('SCHEDULE_UPDATE', 'Actualización de horario'), ('SYSTEM_AVAILABLE', 'Sistema disponible'), ('SYSTEM_UNAVAILABLE', 'Sistema no disponible'), ('API_DOCS_OK', 'Documentación API disponible'), ('API_DOCS_FAIL', 'Documentación API no disponible')], max_length=50, verbose_name='Tipo de evento')),
                ('source', models.CharField(default='SACARF', max_length=20, verbose_name='Fuente')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del usuario')),
                ('user_role', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rol del usuario')),
                ('action', models.CharField(max_length=100, verbose_name='Acción')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de entidad')),
                ('entity_id', models.CharField(blank=True, max_length=50, verbose_name='ID de entidad')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Valor anterior')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha del evento')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recolección')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta original')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type'], name='collector_a_event_t_5a04ee_idx'), models.Index(fields=['timestamp'], name='collector_a_timesta_c5adcc_idx'), models.Index(fields=['user_email'], name='collector_a_user_em_b273c6_idx')],
            },
        ),
    ]
