# Generated by Django 4.2.30 on 2026-06-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('AUTOMATIC', 'Automático'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Tipo de informe')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('quality_scores', models.JSONField(default=dict, verbose_name='Puntajes de calidad')),
                ('findings_summary', models.JSONField(default=dict, verbose_name='Resumen de hallazgos')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Archivo PDF')),
            ],
            options={
                'verbose_name': 'Informe de auditoría',
                'verbose_name_plural': 'Informes de auditoría',
                'ordering': ['-generated_at'],
            },
        ),
    ]
